### ISSUE TITLE
Question: Does this support Magento 2.4?

### ISSUE THREAD

**Issue by irnjunior** [Genaker/TerraformMagentoCloud#12]
Does this support Magento 2.4?

**Comment by Genaker** [comment]
It supports Magento 2.4, 2.5 and Magento 3. It is cloud infrastructure as a
code you can’t install on it whatever you want. Read me document has
explanation.

**Comment by irnjunior** [comment]
Thanks!

**Comment by Genaker** [comment]
it supports not only magento
