### ISSUE TITLE
Cant execute terragrunt apply-all

### ISSUE THREAD

**Issue by selcuk-cofe** [Genaker/TerraformMagentoCloud#15]
Hi there , when I execute `terragrunt apply-all` after install all dependency under cloud/production directory

Im getting for each modules below error.

Cannot process module Module /Users/selcukkubur/Downloads/TerraformMagentoCloud-master 2/cloud/production/redis-securitygroup (excluded: false, dependencies: [/Users/selcukkubur/Downloads/TerraformMagentoCloud-master 2/cloud/production/magento-cloud]) because one of its dependencies, Module /Users/selcukkubur/Downloads/TerraformMagentoCloud-master 2/cloud/production/magento-cloud (excluded: false, dependencies: [/Users/selcukkubur/Downloads/TerraformMagentoCloud-master 2/cloud/production/aws-data]), finished with an error: Cannot process module Module /Users/selcukkubur/Downloads/TerraformMagentoCloud-master 2/cloud/production/magento-cloud (excluded: false, dependencies: [/Users/selcukkubur/Downloads/TerraformMagentoCloud-master 2/cloud/production/aws-data]) because one of its dependencies, Module /Users/selcukkubur/Downloads/TerraformMagentoCloud-master 2/cloud/production/aws-data (excluded: false, dependencies: []), finished with an error: 1 error occurred:
        * exit status 1

**Comment by Genaker** [comment]
Check a terraform, terragrunt versions. This repo requires older versions.

**Comment by psdevhh** [comment]
Hi @Genaker, first of all thanks for posting this repository. Could you please share which terraform / terragrunt versions work for you?

I've tried various combinations of older and newer terraform / terragrunt version combinations now and all result in different errors that seem to be related to version mismatches between them, including errors similar to those in OP's post. Any help on what version combination actually DOES work would be greatly appreciated.

**Comment by Genaker** [comment]
Hi, Patrick. Use branch minimal. And any new version. It has setup
terraform script.

**Comment by psdevhh** [comment]
Hey, thanks for the quick response. I can confirm that with the minimal branch both `terragrunt run-all apply` & `destroy` work with the newest terraform / terragrunt versions (1.0.8 / 0.33.1). Great! 👍

**Comment by Genaker** [comment]
Thanks for the response. We are open to contributors. You can Add/Create
bugs. Also, you are welcome to contribute fixes.
