### ISSUE TITLE
EC2 instances don't have access to internet

### ISSUE THREAD

**Issue by polkunus** [Genaker/TerraformMagentoCloud#17]
I can't follow the instructions on https://github.com/Genaker/Magento-AWS-Linux-2-Installation because none of the instances have any ability to use the commands as they don't have internet access. wget or yum update or ping doesn't work. I also cannot ssh and have to use the CLI on aws because there is no key pair.

**Comment by polkunus** [comment]
I also don't understand what any of this is https://github.com/Genaker/TerraformMagentoCloud/issues/4 I find it to be important as I do have to implement an ssl cert.

**Comment by polkunus** [comment]
How do you stop the instances? Every time I try stopping it, new instances pop up and it costs money. Instead of disabling the auto scaling groups, is there a button that just chills everything out?

It seems like every single time I stop them it gets terminated and all data gets lost. How do I keep the data saved on ec2? I feel like I'm not deploying magento right. What are the other ec2 nodes for if magento is on the webnode?

I was able to finally install magento by adding a allow all rule for outgoing in the security groups for the webnode.

**Comment by Genaker** [comment]
To stop the instance you need change Auto Scaling group capacity to 0. If
you just stop it it will create new one and maintain the same size 1

**Comment by polkunus** [comment]
Thanks for the follow up. How would I ftp into the ec2 instance to modify files and upload data? There is no key pair. I feel like I'm not really doing something correctly as it seems pretty dangerous that stopping the servers wipes your data entirely and automatically. 

If I followed the instructions on here and the other magento repository, are no other configurations needed to fully utilize the features of this repo of a autoscaling magento with varnish cache? And if so, is most of the system administration is interacting with the webnode?

Sorry for the questions, I am a novice at this. Very very lost.

**Comment by Genaker** [comment]
If doesn’t have ftp. Look for sftp/ssh. It has insurance for varnish you
need to use target group to connect the instances.

**Comment by polkunus** [comment]
Thanks I will look into whatever target groups are.

As for connecting ssh, I still don't understand how that'd work as none of the instances have keynames and from my experience you can only assign keypairs (pems) when creating the instance.

**Comment by Genaker** [comment]
I don’t remember exactly how it works. Probably you need add key in the AWS
account and to the Terraform code.

**Comment by polkunus** [comment]
Ok I'll try to figure that out. Thanks again.

I have an ecommerce website that is nearly dormant most of the month with 2-5 visitors a day but about 2 days of the month has around 35k clicks each in about an hour time, is there any way i can further downsize the application, possibly even make the instances types smaller on the off days without screwing things up?

**Comment by Genaker** [comment]
I don’t think this solution can help you. It is really complex and
expensive: you need separate DB server, Redis, ElasticSearch server. The
best is to use this approach:

https://link.medium.com/TXGHNfMEFjb

**Comment by polkunus** [comment]
Oh great, really appreciate you putting me in the right direction. I don't my sparing the expense for a solution that can provide the numbers during the active peaks of 35k concurrent users, but like the idea of active scalability so I only pay for what I use when the site is dormant. Is there a reason why you suggest this over the amazon outside of its complexity?

**Comment by Genaker** [comment]
Better price and performance.

**Comment by polkunus** [comment]
Really cool. Thanks. I set it up, but I don't understand how to implement a load balancer and caching, its not in the tutorial.

**Comment by Genaker** [comment]
This is an open source project, please provide/contribute some information
how it works what you fixed etc.

Unfortunately Varnish is outdated technology you can remove it ;)

You need just 1 load balancer with admin and web. Sometimes even Magento
admin node is not required.

You need setup target group with web end admin nodes as a target:

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html
