### ISSUE TITLE
Facing Issue While Setup

### ISSUE THREAD

**Issue by nemesisat** [Genaker/TerraformMagentoCloud#18]
![image](https://user-images.githubusercontent.com/6083351/133922797-c47f90a3-86f8-47c1-8b22-65a55ef35c4b.png)

I have been facing this issue with the version. if I update it to 1.0.7 I am getting this error very weird.

![image](https://user-images.githubusercontent.com/6083351/133922882-6dde0287-6595-4801-a39e-2fc8d35fe3a2.png)

**Comment by Genaker** [comment]
It doesn’t support 1.0.7

**Comment by nemesisat** [comment]
i have tried with lower version as well it says 

![image](https://user-images.githubusercontent.com/6083351/133959413-f8b85c92-af14-47d6-a490-bfbd289b076a.png)

**Comment by Genaker** [comment]
Clear the cache. Cache was created by bigger version. Also solution doesn’t
have any support or warranty.
