### ISSUE TITLE
Could not read from remote repository.

### ISSUE THREAD

**Issue by delkant** [Genaker/TerraformMagentoCloud#2]
Hi! thank you so much for this great project!

I am having some issues running the script. I am running it from a mac os. Pls help!

error downloading 'ssh://git@github.com/terraform-aws-modules/terraform-aws-vpc.git?ref=v2.31.0': /usr/local/bin/git exited with 128: Cloning into '/Users/xxx/mshop/TerraformMagentoCloud/cloud/production/magento-cloud/.terragrunt-cache/WwNABLWZOHakEXUfCoyeQxKwfU8/BoKn_3NNiOJEg4PmxaP5wYFi3M8'..
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by delkant** [comment]
I solved the problem adding a [SSH key](https://github.com/settings/keys) to my github account.

**Comment by Genaker** [comment]
Thanks for submitting this issue. I made some ReadMe changest to clarify this:

https://github.com/Genaker/TerraformMagentoCloud#how-to-use-it

```
Step 0. Terraform use the SSH protocol to clone the modules, configured SSH keys will be used automatically. Add SSH key to github account. (https://help.github.com/en/enterprise/2.15/user/articles/adding-a-new-ssh-key-to-your-github-account)

Step 1. Set credential. By default, access credentials to AWS account should be set using environment variables:

     export AWS_DEFAULT_REGION=us-west-1
```

**Comment by delkant** [comment]
I actually have more problems on my mac. I had to change all source properties in .hcl files 
**from:**
terraform {
-  source = "git::git@github.com:terraform-aws-modules/terraform-aws-autoscaling.git?ref=v3.4.0"
**to:**
+  source = "git::https://github.com/terraform-aws-modules/terraform-aws-autoscaling.git?ref=v3.4.0"
 }

using: git::https://github.com/ fixed the error: git@github.com: Permission denied (publickey).

**Comment by Genaker** [comment]
Thanks, I can add this to the documentation
