### ISSUE TITLE
Failed to deploy default cloud production

### ISSUE THREAD

**Issue by vujcec** [Genaker/TerraformMagentoCloud#31]
Please advise how to successfully run, many thanks. 

username@computer cloud % cd production
username@computer production % terragrunt apply-all                   
WARN[0000] 'apply-all' is deprecated. Running 'terragrunt run-all apply' instead. Please update your workflows to use 'terragrunt run-all apply', as 'apply-all' may be removed in the future! 
INFO[0000] The stack at /Users/username/TerraformMagentoCloud/cloud/production will be processed in the following order for command apply:
Group 1
- Module /Users/username/TerraformMagentoCloud/cloud/production/aws-data

Group 2
- Module /Users/username/TerraformMagentoCloud/cloud/production/magento-cloud

Group 3
- Module /Users/username/TerraformMagentoCloud/cloud/production/loadbalancer-internal-securitygroup
- Module /Users/username/TerraformMagentoCloud/cloud/production/loadbalancer-internet-securitygroup
- Module /Users/username/TerraformMagentoCloud/cloud/production/mysql-rds-securitygroup
- Module /Users/username/TerraformMagentoCloud/cloud/production/redis-securitygroup
- Module /Users/username/TerraformMagentoCloud/cloud/production/ssh22-securitygroup
- Module /Users/username/TerraformMagentoCloud/cloud/production/varnishnode-securitygroup
- Module /Users/username/TerraformMagentoCloud/cloud/production/webnode-securitygroup

Group 4
- Module /Users/username/TerraformMagentoCloud/cloud/production/mysql
- Module /Users/username/TerraformMagentoCloud/cloud/production/varnish-loadbalanser
- Module /Users/username/TerraformMagentoCloud/cloud/production/webnode-loadbalancer

Group 5
- Module /Users/username/TerraformMagentoCloud/cloud/production/adminwebnode-asg
- Module /Users/username/TerraformMagentoCloud/cloud/production/varnishcacheproxynode-asg
- Module /Users/username/TerraformMagentoCloud/cloud/production/webnode-asg
 
Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n) y

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v5.32.1...
- Installed hashicorp/aws v5.32.1 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
╷
│ Error: Unsupported argument
│ 
│   on main_providers.tf line 6, in provider "aws":
│    6:   skip_get_ec2_platforms      = true
│ 
│ An argument named "skip_get_ec2_platforms" is not expected here.
╵
ERRO[0011] terraform invocation failed in /Users/username/TerraformMagentoCloud/cloud/production/aws-data/.terragrunt-cache/TjIKeX5F6G245P3dU_Hu_trJtDU/p7a5AuRttXXYN01031kiejHGoeU  prefix=[/Users/username/TerraformMagentoCloud/cloud/production/aws-data]...

**Comment by Genaker** [comment]
You need to use proper version of terraform/terragrunt

**Comment by vujcec** [comment]
terragrunt version 0.54.18
Terraform v1.6.6
on darwin_arm64

MacBook M1

**Comment by Genaker** [comment]
You need to use


   - Terraform 0.12  <https://www.terraform.io/>
   - Terragrunt 0.19  <https://github.com/gruntwork-io/terragrunt>

**Comment by vujcec** [comment]
Installed required versions, terragrunt.hcl below is displaying errors or?

username@computer production % terragrunt -v                                                                                                        
terragrunt version v0.19.0
username@computer production % terraform --version
Terraform v1.2.0
on darwin_arm64
Your version of Terraform is out of date! The latest version
is 1.7.0. You can update by downloading from https://www.terraform.io/downloads.html
username@computer production % terragrunt run-all apply                                    
[terragrunt] [/Users/username/TerraformMagentoCloud/cloud/production] 2024/01/18 17:12:18 Running command: terraform --version
[terragrunt] 2024/01/18 17:12:19 Reading Terragrunt config file at /Users/username/TerraformMagentoCloud/cloud/production/terragrunt.hcl
[terragrunt] 2024/01/18 17:12:19 /Users/username/TerraformMagentoCloud/cloud/production/terragrunt.hcl:1,1-7: Unsupported block type; Blocks of type "locals" are not expected here., and 7 other diagnostic(s)

**Comment by Genaker** [comment]
So, you need to upgrade the version and adapt the code to match the newest
version.

**Comment by Genaker** [comment]
.
