### ISSUE TITLE
Change ASG with ECS question

### ISSUE THREAD

**Issue by avra911** [Genaker/TerraformMagentoCloud#7]
Hello,

In which step the ASG can be changed with ECS. Do you mind sharing a few details or docs about it.

Thank you,
Razvan

**Comment by Genaker** [comment]
check this manual: 
http://blog.shippable.com/setup-a-container-cluster-on-aws-with-terraform-part-2-provision-a-cluster

https://github.com/trussworks/terraform-aws-ecs-cluster

**Comment by avra911** [comment]
Thank you, @Genaker , that is very helpful.

Best,
Razvan
