### ISSUE TITLE
No access from Load Balancer neither from instance public IP

### ISSUE THREAD

**Issue by juancarloscruzd** [Genaker/TerraformMagentoCloud#9]
Hello,
I've deployed everything successfully, however I can't connect to the site. 
I've tried looking at Security groups and all seems OK.
Any known issue after a fresh install and not possible to connect to the site?

Thanks

**Comment by Genaker** [comment]
This repo doesn't have installed Magento you need to use your own image. This project idea is to provide infrastructure for Magento not install it.  You can install it using SSH or SSM or User Data

**Comment by Genaker** [comment]
This repo doesn't have installed Magento it is infrastructure provisioning only

**Comment by polkunus** [comment]
How do I install magento, when I am in the EC2 console I can't yum update or wget or anything. I can't ssh because there is no key pair

**Comment by Genaker** [comment]
What do you mean EC2 console? You should ssh to the insurance using key and
public IP address.

**Comment by polkunus** [comment]
Sorry what do you mean by "the insurance" how do I ssh to it? Im directly sshing to the webnode instance.

**Comment by Genaker** [comment]
Correct directly to the web-node. Instance is a web-node,server,vps, Ec2

**Comment by polkunus** [comment]
Oh it was a typo, I see, thanks for your time egor.
